#!/bin/sh
${CVI_SHOPTS}
#
# Start fastboot process 
#

case "$1" in
	start)
        if [ -f /bin/store_init_time ]; then
            /bin/store_init_time &		# User defined fastboot process
            usleep 10000
        fi
        ;;

	stop)
        ;;

	restart|reload)
        ;;

	*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?