ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
update_config=1

network={
	ssid="H3C-WiFi5-3B7C-5G"
	psk="Cvitek123456"
	key_mgmt=WPA-PSK
	auth_alg=OPEN
	priority=10
}

network={
	ssid="H3C-WiFi5-3B7C"
	psk="Cvitek123456"
	key_mgmt=WPA-PSK
	auth_alg=OPEN
	priority=5
}
